# Meta Data for SEO

## Homepage
title = "Home"
titleSeparator = "-"
titleAddition = "DevOps Security Survey"
description = "Too many approaches to security focus on what developers and operators do wrong, but this survey focuses on what we're doing right so we can amplify it."

## Open Graph
images = ["doks.png"]
ogLocale = "en_US"
domainTLD = "securitysurvey.dev"
titleHome = "DevOps Security Survey"

## Twitter Cards
twitterSite = "@thedevopsurvey" ## <- todo: needs updating
twitterCreator = "@thedevopsurvey" ## <- todo: needs updating

## JSON-LD
# schemaType = "Person"
schemaType = "Organization"
schemaName = "DevOps Security Survey"
schemaAuthor = "Henk Verlinde" ## <- todo: needs updating
schemaAuthorTwitter = "https://twitter.com/henkverlinde" ## <- todo: needs updating
schemaAuthorLinkedIn = "https://www.linkedin.com/in/henkverlinde/" ## <- todo: needs updating
schemaAuthorGitHub = "https://github.com/h-enk" ## <- todo: needs updating
schemaLocale = "en-US"
schemaLogo = "logo-doks.png" ## <- todo: needs updating
schemaLogoWidth = 512
schemaLogoHeight = 512
schemaImage = "doks.png" ## <- todo: needs updating
schemaImageWidth = 1280
schemaImageHeight = 640
schemaTwitter = "https://twitter.com/getdoks" ## <- todo: needs updating
schemaLinkedIn = ""
schemaGitHub = "https://github.com/h-enk/doks" ## <- todo: needs updating
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"
smallLimit = "300"

# Footer
footer = "Sponsored by <a href='https://blubracket.com/'>BluBracket</a>"

# Feed
copyRight = "Copyright (c) 2021 BluBracket"

# Edit Page
# repoHost [Github | Gitea | GitLab] is used for building the edit link based on git hoster
repoHost = "GitHub"
docsRepo = "https://github.com/misterbisson/securitysurvey.dev"
docsRepoBranch = "main"
editPage = true

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  flexSearch = true
  darkMode = true
  bootStrapJs = true
  breadCrumb = false
  highLight = true
  kaTex = false
  collapsibleSidebar = true
  multilingualMode = false
  docsVersioning = false
